# Generated by Django 4.1.3 on 2022-11-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediopago', models.CharField(max_length=50)),
                ('monto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pronosticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeon', models.CharField(max_length=50)),
                ('subcampeon', models.IntegerField()),
                ('goleador', models.EmailField(max_length=254)),
            ],
        ),
    ]
